### ISSUE TITLE
Missing build/release for Python 3.11.2 / 3.10.10

### ISSUE THREAD

**Issue by msw-kialo** [containerbase/python-prebuild#20]
Python 3.11.2 was released on [the 8th of February](https://www.python.org/downloads/release/python-3112/). Renovate promptly started [the upgrade](https://github.com/containerbase/python-prebuild/commit/fdc38860ee8b6ad48d7b64f8977dd3096abc44c3). However, the automerge of these successful builds appears to be stuck for some reason (see #1).

The same appears to be the case for 3.10.10.

It would be nice if you could fix this so that we can use the newest Python patch version.

**Comment by msw-kialo** [comment]
@viceice Would it be possible to look into this? Sorry to ping you, but I am not sure whether issues are discovered here.

**Comment by viceice** [comment]
should be available Ina few minutes
